export const HAVERFORD_DOMAIN = "@haverford.edu";
export const MAX_TITLE_LENGTH = 100;
export const MAX_DESCRIPTION_LENGTH = 2000;
export const MAX_LOCATION_LENGTH = 200;
export const MAX_HOST_DISPLAY_NAME_LENGTH = 100;
export const MAX_BLAST_LENGTH = 500;
export const MAX_IMAGE_SIZE = 50 * 1024 * 1024; // 50MB
export const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];
export const EVENT_WINDOW_DAYS = 30;
export const MAX_EVENT_MONTHS_AHEAD = 6;
export const APP_NAME = "Acorn";
export const TIMEZONE = "America/New_York";
